swagger: '2.0'
schemes:
  - https
host: api.personio.de
basePath: /v1
info:
  contact:
    x-twitter: PersonioHR
  description: API for reading and writing personnel data incl. data about attendances and absences
  title: Personnel Data
  version: '1.0'
  x-apisguru-categories:
    - enterprise
  x-logo:
    url: 'https://twitter.com/PersonioHR/profile_image?size=original'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/personio/api-docs/master/personio-personnel-data-api.yaml'
      version: '2.0'
  x-providerName: personio.de
  x-serviceName: personnel
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  auth:
    in: header
    name: Authorization
    type: apiKey
paths:
  /company/attendances:
    get:
      description: 'This endpoint is responsible for fetching attendance data for the company employees. It is possible to paginate results, filter by period and/or specific employees. The result will contain a list of attendance periods, structured as defined here.'
      parameters:
        - description: 'First day of the period to be queried. It is inclusive, so the day specified as start_date will also be considered on the results'
          format: date
          in: query
          name: start_date
          required: true
          type: string
        - description: 'Last day of the period to be queried. It is inclusive, so the day specified as end_date will also be considered on the results.'
          format: date
          in: query
          name: end_date
          required: true
          type: string
        - collectionFormat: multi
          description: A list of Personio employee identifiers to filter the results. Only those employees specified here will be returned.
          in: query
          items:
            type: integer
          name: employees
          required: false
          type: array
        - default: 200
          description: Pagination attribute to limit how many attendances will be returned per page
          in: query
          minimum: 1
          name: limit
          required: false
          type: integer
        - default: 0
          description: 'Pagination attribute to identify which page you are requesting, by the form of telling an offset from the first record that would be returned.'
          in: query
          minimum: 0
          name: offset
          required: false
          type: integer
      responses:
        '200':
          description: ''
          examples:
            application/json:
              data:
                - attributes:
                    break: 50
                    comment: I was productive as hell
                    date: '2017-01-17'
                    employee: 325659
                    end_time: '18:00'
                    is_holiday: false
                    is_on_time_off: false
                    start_time: '9:00'
                  type: AttendancePeriod
                - attributes:
                    break: 60
                    date: '2017-01-18'
                    employee: 325660
                    end_time: '18:30'
                    is_holiday: false
                    is_on_time_off: true
                    start_time: '9:30'
                  type: AttendancePeriod
              limit: 200
              offset: 0
              success: true
          schema:
            $ref: '#/definitions/AttendancePeriodsResponse'
    post:
      description: 'This endpoint is responsible for adding attendance data for the company employees. It is possible to add attendances for one or many employees at the same time. The payload sent on the request should be a list of attendance periods, in the form of an array containing attendance period objects.'
      parameters:
        - description: List of attendance periods to create
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/NewAttendancePeriodRequest'
      responses:
        '200':
          description: The attendance periods were created successfully
          examples:
            application/json:
              data:
                message: success
              success: true
          schema:
            $ref: '#/definitions/NewAttendancePeriodResponse'
        '400':
          description: Invalid request
          examples:
            application/json:
              error:
                code: 400
                message: Error when trying to insert Attendances periods rows
              success: true
          schema:
            properties:
              error:
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                type: object
              success:
                type: boolean
            type: object
  /company/employees:
    get:
      description: List Employees
      parameters:
        - description: '[In development] Query string to perform search on. Returns all employees if not present. Can also be used with custom attributes, e.g. `dynamic_9382=abcd`'
          in: query
          name: query
          required: false
          type: string
        - description: '[In development] Attributes to be returend for employees found. Returns all available attributes if not present. Pass `attributes` multiple times of needed.'
          in: query
          items: {}
          name: attributes
          required: false
          type: array
      responses:
        '200':
          description: ''
          examples:
            application/json:
              data:
                - attributes:
                    contract_end_date:
                      label: Contract ends
                    cost_centers:
                      label: Cost center
                      value:
                        - attributes:
                            id: 320
                            name: Cost Center One
                            percentage: 50
                          type: CostCenter
                        - attributes:
                            id: 321
                            name: Cost Center Two
                            percentage: 50
                          type: CostCenter
                    created_at:
                      label: created_at
                      value: '2016-10-20T16:15:55+0200'
                    department:
                      label: Department
                      value:
                        attributes:
                          name: Marketing
                        type: Department
                    dynamic_21827:
                      label: IBAN
                      value: DE98 8989 9898 0000 8989 00
                    dynamic_24407:
                      label: Titel
                      value: Dr
                    email:
                      label: Email
                      value: andreas.anderson@demo.com
                    employment_type:
                      label: Employment type
                      value: internal
                    first_name:
                      label: First name
                      value: Andreas
                    fix_salary:
                      label: Fix salary
                      value: 4000
                    gender:
                      label: Gender
                      value: male
                    hire_date:
                      label: Hire date
                      value: '2012-02-01T00:00:00+0100'
                    hourly_salary:
                      label: Hourly salary
                      value: 0
                    id:
                      label: id
                      value: 83752
                    last_name:
                      label: Last name
                      value: Anderson
                    last_working_day:
                      label: Last working day
                      value: '2017-02-28T00:00:00+0200'
                    office:
                      label: Office
                      value:
                        attributes:
                          name: Munich
                        type: Office
                    position:
                      label: Position
                      value: Online Marketing Specialist
                    probation_period_end:
                      label: Probation period end
                      value: '2012-07-31T00:00:00+0200'
                    status:
                      label: Status
                      value: active
                    supervisor:
                      label: Supervisor
                      value:
                        attributes:
                          email:
                            label: Email
                            value: max.mustermann@example.org
                          first_name:
                            label: First name
                            value: Max
                          id:
                            label: id
                            value: 423506
                          last_name:
                            label: Last name
                            value: Mustermann
                        type: Employee
                    termination_date:
                      label: Termination date
                    termination_reason:
                      label: Termination reason
                      value: ''
                    termination_type:
                      label: Termination type
                      value: ''
                    vacation_day_balance:
                      label: Vacation day balance
                      value: 28.5
                    weekly_working_hours:
                      label: Weekly hours
                      value: '40'
                  type: Employee
              success: true
          schema:
            $ref: '#/definitions/EmployeesResponse'
  '/company/employees/{employee_id}':
    get:
      description: Employee
      parameters:
        - description: Numeric `id` of the employee
          format: integer
          in: path
          name: employee_id
          required: true
          type: number
      responses:
        '200':
          description: ''
          examples:
            application/json:
              data:
                attributes:
                  contract_end_date:
                    label: Contract ends
                  cost_centers:
                    label: Cost center
                    value:
                      - attributes:
                          id: 320
                          name: Cost Center One
                          percentage: 50
                        type: CostCenter
                      - attributes:
                          id: 321
                          name: Cost Center Two
                          percentage: 50
                        type: CostCenter
                  created_at:
                    label: created_at
                    value: '2016-10-20T16:15:55+0200'
                  department:
                    label: Department
                    value:
                      attributes:
                        name: Marketing
                      type: Department
                  dynamic_21827:
                    label: IBAN
                    value: DE98 8989 9898 0000 8989 00
                  dynamic_24407:
                    label: Titel
                    value: Dr
                  email:
                    label: Email
                    value: andreas.anderson@demo.com
                  employment_type:
                    label: Employment type
                    value: internal
                  first_name:
                    label: First name
                    value: Andreas
                  fix_salary:
                    label: Fix salary
                    value: 4000
                  gender:
                    label: Gender
                    value: male
                  hire_date:
                    label: Hire date
                    value: '2012-02-01T00:00:00+0100'
                  hourly_salary:
                    label: Hourly salary
                    value: 0
                  id:
                    label: id
                    value: 83752
                  last_name:
                    label: Last name
                    value: Anderson
                  last_working_day:
                    label: Last working day
                    value: '2017-02-28T00:00:00+0200'
                  office:
                    label: Office
                    value:
                      attributes:
                        name: Munich
                      type: Office
                  position:
                    label: Position
                    value: Online Marketing Specialist
                  probation_period_end:
                    label: Probation period end
                    value: '2012-07-31T00:00:00+0200'
                  status:
                    label: Status
                    value: active
                  supervisor:
                    label: Supervisor
                    value:
                      attributes:
                        email:
                          label: Email
                          value: max.mustermann@example.org
                        first_name:
                          label: First name
                          value: Max
                        id:
                          label: id
                          value: 423506
                        last_name:
                          label: Last name
                          value: Mustermann
                      type: Employee
                  termination_date:
                    label: Termination date
                  termination_reason:
                    label: Termination reason
                    value: ''
                  termination_type:
                    label: Termination type
                    value: ''
                  vacation_day_balance:
                    label: Vacation day balance
                    value: 28.5
                  weekly_working_hours:
                    label: Weekly hours
                    value: '40'
                type: Employee
              success: true
          schema:
            $ref: '#/definitions/EmployeeResponse'
  '/company/time-off/{time_off_id}':
    get:
      description: Absence Period
      parameters:
        - description: Numeric `id` of the absence period
          format: integer
          in: path
          name: time_off_id
          required: true
          type: number
      responses:
        '200':
          description: ''
          examples:
            application/json:
              data:
                attributes:
                  certificate:
                    status: not-required
                  created_at: '2017-01-17T10:32:18+0100'
                  days_count: 3
                  employee:
                    attributes:
                      email:
                        label: Email
                        value: michael.miller@demo.com
                      first_name:
                        label: First name
                        value: Michael
                      last_name:
                        label: Last name
                        value: Miller
                    type: Employee
                  end_date: '2017-12-29T00:00:00+0100'
                  half_day_end: 0
                  half_day_start: 0
                  start_date: '2017-12-27T00:00:00+0100'
                  status: approved
                  time_off_type:
                    attributes:
                      name: Vacation
                    type: TimeOffType
                type: TimeOffPeriod
              success: true
          schema:
            $ref: '#/definitions/AbsencePeriodResponse'
  /company/time-offs:
    get:
      description: List All Absence Periods
      parameters: []
      responses:
        '200':
          description: ''
          examples:
            application/json:
              data:
                - attributes:
                    certificate:
                      status: not-required
                    created_at: '2017-01-17T10:32:18+0100'
                    days_count: 3
                    employee:
                      attributes:
                        email:
                          label: Email
                          value: michael.miller@demo.com
                        first_name:
                          label: First name
                          value: Michael
                        last_name:
                          label: Last name
                          value: Miller
                      type: Employee
                    end_date: '2017-12-29T00:00:00+0100'
                    half_day_end: 0
                    half_day_start: 0
                    start_date: '2017-12-27T00:00:00+0100'
                    status: approved
                    time_off_type:
                      attributes:
                        name: Vacation
                      type: TimeOffType
                  type: TimeOffPeriod
              success: true
          schema:
            $ref: '#/definitions/AbsencePeriodsResponse'
definitions:
  AbsencePeriodResponse:
    type: object
  AbsencePeriodsResponse:
    allOf:
      - $ref: '#/definitions/Response'
      - properties:
          data:
            properties:
              attributes:
                items:
                  properties:
                    certificate:
                      properties:
                        status:
                          type: string
                      type: object
                    created_at:
                      type: string
                    days_count:
                      type: number
                    employee:
                      properties:
                        attributes:
                          items:
                            properties:
                              email:
                                type: string
                              first_name:
                                type: string
                              last_name:
                                type: string
                            type: object
                          type: array
                        type:
                          type: string
                      type: object
                    end_date:
                      type: string
                    half_day_end:
                      type: number
                    half_day_start:
                      type: number
                    start_date:
                      type: string
                    status:
                      type: string
                    time_off_type:
                      properties:
                        attributes:
                          items:
                            properties:
                              name:
                                type: string
                            type: object
                          type: array
                        type:
                          type: string
                      type: object
                  type: object
                type: array
              type:
                type: string
            required:
              - type
              - attributes
            type: object
        type: object
    title: List All Absence Periods response
    type: object
  AttendancePeriodsResponse:
    allOf:
      - $ref: '#/definitions/Response'
      - properties:
          data:
            items:
              properties:
                attributes:
                  items:
                    properties:
                      break:
                        type: integer
                      comment:
                        type: string
                      date:
                        format: date
                        type: string
                      employee:
                        type: integer
                      end_time:
                        pattern: '^\d\d:\d\d$'
                        type: string
                      is_holiday:
                        type: boolean
                      is_on_time_off:
                        type: boolean
                      start_time:
                        pattern: '^\d\d:\d\d$'
                        type: string
                    required:
                      - employee
                      - date
                      - start_time
                      - end_time
                      - break
                      - comment
                      - is_holiday
                      - is_on_time_off
                    type: object
                  type: array
                type:
                  type: string
              required:
                - type
                - attributes
              type: object
            type: array
          limit:
            type: integer
          offset:
            type: integer
        type: object
    title: List All Attenance Periods response
    type: object
  Attribute:
    properties:
      label:
        type: string
      value:
        type: object
    required:
      - label
      - value
    type: object
  CostCenters:
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        items:
          properties:
            attributes:
              items:
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  percentage:
                    type: number
                type: object
              type: array
            type:
              type: string
          type: object
        type: array
    type: object
  Department:
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        properties:
          attributes:
            items:
              properties:
                name:
                  type: string
              type: object
            type: array
          type:
            type: string
        type: object
    type: object
  Employee:
    properties:
      attributes:
        items:
          properties:
            contract_end_date:
              $ref: '#/definitions/Attribute'
            cost_centers:
              $ref: '#/definitions/CostCenters'
            created_at:
              $ref: '#/definitions/Attribute'
            department:
              $ref: '#/definitions/Department'
            email:
              $ref: '#/definitions/Attribute'
            employment_type:
              $ref: '#/definitions/Attribute'
            first_name:
              $ref: '#/definitions/Attribute'
            fix_salary:
              $ref: '#/definitions/Attribute'
            gender:
              $ref: '#/definitions/Attribute'
            hire_date:
              $ref: '#/definitions/Attribute'
            hourly_salary:
              $ref: '#/definitions/Attribute'
            id:
              $ref: '#/definitions/Attribute'
            last_name:
              $ref: '#/definitions/Attribute'
            office:
              $ref: '#/definitions/Office'
            position:
              $ref: '#/definitions/Attribute'
            probation_period_end:
              $ref: '#/definitions/Attribute'
            status:
              $ref: '#/definitions/Attribute'
            supervisor:
              $ref: '#/definitions/Supervisor'
            termination_date:
              $ref: '#/definitions/Attribute'
            termination_reason:
              $ref: '#/definitions/Attribute'
            termination_type:
              $ref: '#/definitions/Attribute'
            vacation_day_balance:
              $ref: '#/definitions/Attribute'
            weekly_working_hours:
              $ref: '#/definitions/Attribute'
          type: object
        type: array
      type:
        type: string
    required:
      - type
      - attributes
    type: object
  EmployeeResponse:
    allOf:
      - $ref: '#/definitions/Response'
      - properties:
          data:
            allOf:
              - $ref: '#/definitions/Employee'
            type: object
        type: object
    title: Employee
  EmployeesResponse:
    allOf:
      - $ref: '#/definitions/Response'
      - properties:
          data:
            items:
              allOf:
                - $ref: '#/definitions/Employee'
              type: object
            type: array
        type: object
    title: List of Employees
  NewAttendancePeriodRequest:
    example:
      attendances:
        - break: 120
          date: '2017-01-18'
          employee: 1234
          end_time: '18:00'
          start_time: '8:00'
        - break: 35
          comment: I was productive as hell
          date: '2017-01-17'
          employee: 1235
          end_time: '12:00'
          start_time: '9:00'
    properties:
      attendances:
        items:
          properties:
            break:
              description: Break in minutes
              format: int32
              type: integer
            comment:
              description: Optional comment
              type: string
            date:
              description: Attendance date as YYYY-MM-DD
              format: date
              type: string
            employee:
              description: Employee identifier
              type: integer
            end_time:
              description: 'End time as HH:MM'
              pattern: '^\d\d:\d\d$'
              type: string
            start_time:
              description: 'Start time as HH:MM'
              pattern: '^\d\d:\d\d$'
              type: string
          required:
            - employee
            - date
            - start_time
            - end_time
            - break
            - comment
          type: object
        type: array
    title: Create a New Attendance Period request
    type: object
  NewAttendancePeriodResponse:
    allOf:
      - $ref: '#/definitions/Response'
      - properties:
          data:
            properties:
              message:
                type: string
            type: object
        type: object
    type: object
  Office:
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        properties:
          attributes:
            items:
              properties:
                name:
                  type: string
              type: object
            type: array
          type:
            type: string
        type: object
    type: object
  Response:
    properties:
      data:
        type: object
      success:
        type: boolean
    required:
      - success
      - data
    title: Default response object
    type: object
  Supervisor:
    allOf:
      - $ref: '#/definitions/Attribute'
    properties:
      value:
        $ref: '#/definitions/Employee'
    type: object
